extern int flag__print_tokens;
extern int flag__print_ast;
extern int flag__print_ast_json;
extern int flag__print_reg_alloc;
extern int flag__print_code;
extern int flag__print_opt;
extern int flag__print_all;
extern int flag__print_help;
extern int flag__no_opt;
extern int flag__inline;
extern int flag__no_output;
extern int flag__if_jitless;
extern int flag__run_tests;
extern int flag__code_header_printed;
void parse_args(int argc, char **argv);
